// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'film_info': string;
  'genre_label': string;
  'genres': string;
  'overview': string;
  'poster': string;
  'release_date': string;
  'root': string;
  'stars': string;
  'stars_container': string;
  'title': string;
  'vote_average': string;
}
export const cssExports: CssExports;
export default cssExports;
